## Настройки ВК
vk:
  group_id: idГруппыБезМинуса
  token: "токен"

## Настройки бота
settings:
  colon: true # Использование двоеточия в командах бота

## Заблокированые команды в боте
block_cmds:
  - 'stop'

## Игроки которых нельзя кикнуть в боте
white_players:
  - 'TheHelpix'